name: Deploy Pipeline To Heroku

on:
  push:
    branches: [main]
  pull_request:
    branches:  [main]
    types: [opened, synchronize]

jobs:
  avoid_redundancy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  install:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

  lint:
    needs: install
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run eslint

  test:
    needs: lint
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: ['4.4']
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install dependencies
        run: npm ci

      - name: Tests
        run: npm run test

  deploy:
    needs: test
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Deploy to Heroku
        if ${{ github.event_name == 'push' }}
          uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: ${{secrets.HEROKU_APP}}
            heroku_email: ${{secrets.HEROKU_EMAIL}}
            healthcheck: "https://${{secrets.HEROKU_APP}}.herokuapp.com/health"
            checkstring: "ok"
            rollbackonhealthcheckfailed: true
            buildpack: "https://github.com/heroku/heroku-buildpack-nodejs"

